name = "toffoli_proofs"
version = "0.1.0"
defaultTargets = ["Toffoli"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "0e265f2ff3987cdc4757407f55f3dbfc06d52ab5"

[[lean_lib]]
name = "Toffoli"
