import Mathlib.LinearAlgebra.AffineSpace.AffineEquiv
import Mathlib.Algebra.Group.Subgroup.Lattice

namespace Toffoli

/-- The permutations generated by all affine equivalences and one chosen gate.
For a register `V = Fin n → R`, an affine equivalence has an invertible
`R`-linear part and a translation. This also covers composite modular
alphabets: invertibility is over the ring, with no field assumption.
The chosen gate will be the swap of two labels on one coordinate. -/
def affineSwapGroup (R : Type*) [CommRing R] {V : Type*}
    [AddCommGroup V] [Module R V] (τ : Equiv.Perm V) : Subgroup (Equiv.Perm V) :=
  Subgroup.closure (Set.range (AffineEquiv.toEquiv : (V ≃ᵃ[R] V) → Equiv.Perm V) ∪ {τ})

end Toffoli
