import Toffoli.Universality.AffineSwapConjugateMem
import Toffoli.Universality.RegisterTargetSwap
import Toffoli.Universality.CoordinateGeneration
import Toffoli.Foundations.CoordinateShearApply

namespace Toffoli
open scoped Classical

/-- Each accumulator primitive belongs to the group generated by affine
maps and the fixed target swap. Local control swaps are moved to their wire
using the already proved one-wire generation theorem. -/
theorem multi_gate_generation {K : Type*} [Field K] {n : ℕ}
    (hone : affineSwapGroup K (Equiv.swap (0 : K) 1) = ⊤) (g : MultiGate K n) :
    ∃ σ ∈ affineSwapGroup K (targetSwap (C := Controls K n) (K := K)),
      ∀ s, σ s = g.eval s := by
  classical
  let G := affineSwapGroup K (targetSwap (C := Controls K n) (K := K))
  have affine_mem (e : (Controls K n × K) ≃ᵃ[K] (Controls K n × K)) : e.toEquiv ∈ G :=
    Subgroup.subset_closure (Or.inl ⟨e, rfl⟩)
  cases g with
  | affine e =>
    refine ⟨(e.prodCongr (AffineEquiv.refl K K)).toEquiv, affine_mem _, ?_⟩
    rintro ⟨x, t⟩
    simp [MultiGate.eval, MultiGate.control, MultiGate.increment]
  | swap i a b =>
    let σ := coordinatePermutation i.succ (Equiv.swap a b)
    have hσ := coordinate_generation (0 : Fin (n + 1)) i.succ
      (Equiv.swap (0 : K) 1) (Equiv.swap a b) hone
    have hmem := affine_swap_conjugate_mem (registerJoin (K := K) n).symm
      (coordinatePermutation (0 : Fin (n + 1)) (Equiv.swap (0 : K) 1)) σ hσ
    refine ⟨(registerJoin (K := K) n).symm.toEquiv.permCongr σ,
      by simpa only [register_target_swap] using hmem, ?_⟩
    rintro ⟨x, t⟩
    apply Prod.ext
    · funext j
      change σ (Fin.cons t x) j.succ = (MultiGate.swap i a b).control x j
      by_cases h : j = i
      · subst j
        simp [σ, coordinate_permutation_apply, MultiGate.control]
      · simp [σ, coordinate_permutation_apply, MultiGate.control, h]
    · change σ (Fin.cons t x) 0 = t + 0
      simp [σ, coordinate_permutation_apply, (Fin.succ_ne_zero i).symm]
  | sum i coefficient =>
    let e := ((registerJoin (K := K) n).trans
      (coordinateShear i.succ 0 coefficient (Fin.succ_ne_zero i))).trans
        (registerJoin (K := K) n).symm
    refine ⟨e.toEquiv, affine_mem e, ?_⟩
    rintro ⟨x, t⟩
    change (fun j => (coordinateShear i.succ 0 coefficient (Fin.succ_ne_zero i)
      (Fin.cons t x)) j.succ, (coordinateShear i.succ 0 coefficient
        (Fin.succ_ne_zero i) (Fin.cons t x)) 0) = (x, t + coefficient * x i)
    rw [coordinate_shear_apply]
    simp

end Toffoli
